services:
  papi-frontend:
    build: .
    container_name: site-papi
    ports:
      - "8088:80"
    networks:
      - papi-network
    restart: always

networks:
  papi-network:
    external: true
